# Generated by Django 5.0.1 on 2024-01-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateField(blank=True, null=True, verbose_name='дата создания'),
        ),
    ]
