# Generated by Django 4.2 on 2024-02-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_is_published', 'разрешено менять публикацию товаров')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
